# Generated by Django 5.1.3 on 2024-11-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название книги')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Краткое описание')),
                ('author', models.CharField(default='', max_length=255, verbose_name='Автор')),
                ('genre', models.CharField(default='', max_length=100, verbose_name='Жанр')),
                ('cover', models.ImageField(upload_to='covers/', verbose_name='Обложка')),
            ],
            options={
                'verbose_name': 'Книгу',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
